# Generated by Django 5.0.14 on 2026-01-06 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL amigable)')),
                ('icon', models.CharField(blank=True, help_text="Clase CSS del icono (ej: 'fa-shopping-cart')", max_length=50, verbose_name='Icono')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor = primero)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Código del tema (ej: '1.13', '2.15') para ordenamiento secuencial", max_length=20, unique=True, verbose_name='Código')),
                ('title', models.CharField(help_text="Ej: 'Creación de Cliente', 'Proceso de Facturación'", max_length=200, verbose_name='Título del Tema')),
                ('start_seconds', models.PositiveIntegerField(default=0, help_text='Segundo exacto donde empieza este tema en el video', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inicia en (segundos)')),
                ('description', models.TextField(blank=True, help_text='Notas, instrucciones, contexto. Soporta Markdown.', verbose_name='Descripción')),
                ('location_tag', models.CharField(blank=True, choices=[('piso_1', 'Piso 1'), ('piso_2', 'Piso 2'), ('piso_3', 'Piso 3'), ('piso_4', 'Piso 4'), ('caja', 'Caja'), ('bodega', 'Bodega'), ('cedi', 'CEDI'), ('oficina', 'Oficina'), ('remoto', 'Remoto'), ('general', 'General')], help_text='Contexto físico donde aplica este tema (informativo)', max_length=20, verbose_name='Ubicación/Contexto')),
                ('is_published', models.BooleanField(default=True, help_text='Desmarcar para ocultar este tema del sistema', verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tag')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('topics', models.ManyToManyField(blank=True, related_name='tags', to='core.topic', verbose_name='Temas')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Quiz')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Porcentaje mínimo para aprobar', verbose_name='Puntaje Mínimo (%)')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Dejar en blanco para sin límite', null=True, verbose_name='Tiempo Límite (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(help_text='Selecciona los temas que este quiz evalúa', related_name='quizzes', to='core.topic', verbose_name='Temas Evaluados')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre interno del archivo de video', max_length=200, verbose_name='Título del Video')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('cloudflare', 'Cloudflare Stream')], default='youtube', max_length=20, verbose_name='Plataforma')),
                ('external_id', models.CharField(help_text='ID del video en la plataforma (ej: dQw4w9WgXcQ para YouTube)', max_length=100, verbose_name='ID Externo')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duración total del video en segundos', null=True, verbose_name='Duración (segundos)')),
                ('uploaded_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Subida')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Asset',
                'verbose_name_plural': 'Video Assets',
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'external_id')},
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.ForeignKey(help_text='Video que contiene este tema', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.videoasset', verbose_name='Video'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['code'], name='core_topic_code_78bca1_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category', 'code'], name='core_topic_categor_969775_idx'),
        ),
    ]
