# Generated by Django 5.0.14 on 2026-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoasset',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('cloudflare', 'Cloudflare Stream'), ('drive', 'Google Drive')], default='youtube', max_length=20, verbose_name='Plataforma'),
        ),
    ]
